// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwljtdvlwcxablbtddrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bGp0ZHZsd2N4YWJsYnRkZHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjIyNDYsImV4cCI6MjA2MDYzODI0Nn0.ryxBSMvGL_i-gFOiIcTMND9r8gZ7biWl6VI51Jg-wTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);